// ═══════════════════════════════════════════════════════════════════════════
// CANON — canonical variables (algorithm-math.md §1.1) + knowledge access
// ═══════════════════════════════════════════════════════════════════════════
//
// House rule (skill §1.1): never report a rate without its n. A Rate is
// therefore always {value, n}; a metric the platform didn't give us is null —
// NEVER zero. Knowledge JSON is generated by scripts/sync-knowledge.ts from
// the skill files; nothing here hardcodes a threshold.

import type { Platform } from "@/lib/forecast";
import meta from "./knowledge/_meta.json";
import tiktok from "./knowledge/tiktok.json";
import instagram from "./knowledge/instagram.json";
import youtube from "./knowledge/youtube.json";
import youtubeShort from "./knowledge/youtube_short.json";
import x from "./knowledge/x.json";

// ── rates ───────────────────────────────────────────────────────────────────

/** An estimated probability/rate plus the sample size backing it. */
export interface Rate {
  value: number;
  n: number;
}

export type MaybeRate = Rate | null;

export function rate(value: number | null | undefined, n: number | null | undefined): MaybeRate {
  if (value == null || n == null || !Number.isFinite(value) || !Number.isFinite(n) || n <= 0) return null;
  return { value, n };
}

// ── canonical metric bundles per platform ───────────────────────────────────

export interface ReachSnapshot {
  ageHours: number;
  reach: number; // views as reach proxy (true reach only via creator analytics)
}

export interface CanonicalCommon {
  platform: Platform;
  contentId: string;
  views: number;
  ageHours: number | null;
  /** Time-stamped reach snapshots for wave ratios (velocity track). */
  snapshots: ReachSnapshot[];
  /** Provenance notes that become contract caveats. */
  notes: string[];
}

export interface CanonicalMetrics extends CanonicalCommon {
  // Short-form / video rates (null = platform didn't expose it)
  C_comp: MaybeRate;
  V_vs: MaybeRate;
  H_3s: MaybeRate;
  R_loop: MaybeRate;
  s: MaybeRate; // share rate
  save_rate: MaybeRate;
  SPR: MaybeRate; // DM sends / reach (IG)
  CTR: MaybeRate;
  AVD: MaybeRate; // proportion of video watched
  R_30s: MaybeRate;
  v1: MaybeRate; // first-hour velocity (events/min normalized)
  likes_per_reach: MaybeRate;
  // IG originality
  hasWatermark: boolean | null;
  isRepostHeavy: boolean | null;
  // TikTok region fork
  region: "us" | "global" | null;
  // X realized counts (per-impression weighting happens in math.xScore)
  xCounts: {
    impressions: number;
    likes: number;
    reposts: number;
    replies: number;
    quotes: number;
    bookmarks: number;
    authorReplied: number | null;
    profileEng: number | null;
    dwells: number | null;
    video50: number | null;
    mutes: number | null;
    reports: number | null;
    tweepCred: number | null; // 0–100, manual
  } | null;
}

// ── knowledge access ────────────────────────────────────────────────────────

export interface GateSpec {
  name: string;
  threshold: number;
  phase: number;
  kind: "rate" | "binary" | "score";
  weakFloor?: number;
  killFloor?: number;
}

export interface PlatformKnowledge {
  platform: string;
  calibrationStamp: string;
  syncedAt: string;
  weights: Record<string, number>;
  params: Record<string, number>;
  gates: GateSpec[];
  phaseWindows: Array<{ phase: number; startH: number; endH: number | null }>;
  coaching?: { phase1: string; phase2: string; phase34: string };
}

const KNOWLEDGE: Record<Platform, PlatformKnowledge> = {
  tiktok: tiktok as PlatformKnowledge,
  instagram: instagram as PlatformKnowledge,
  youtube: youtube as PlatformKnowledge,
  youtube_short: youtubeShort as PlatformKnowledge,
  x: x as PlatformKnowledge,
};

export function knowledgeFor(platform: Platform): PlatformKnowledge {
  return KNOWLEDGE[platform];
}

export const UNIVERSAL = meta.universal as { kappa: number; wilsonZ: number; sigmoidK: number; sigmoidM: number };

export interface KnowledgeMeta {
  skillVersion: string;
  calibrationStamp: string;
  syncedAt: string;
  domainAStaleDays: number;
}

export function knowledgeMeta(): KnowledgeMeta {
  return meta as unknown as KnowledgeMeta;
}

/** Days since the skill's calibration stamp ("June 2026" → month start). */
export function knowledgeAgeDays(now: number): number {
  const d = new Date(`${(meta as { calibrationStamp: string }).calibrationStamp} 1`);
  return (now - d.getTime()) / 86_400_000;
}

export function knowledgeIsStale(now: number): boolean {
  return knowledgeAgeDays(now) > (meta as { domainAStaleDays: number }).domainAStaleDays;
}

// ── prediction contract (Phase 4 spec) ──────────────────────────────────────

export type GateVerdict = "pass" | "fail" | "insufficient_evidence";

export interface GateResult {
  name: string;
  value: number | null;
  n: number | null;
  wilson_lb: number | null;
  threshold: number;
  verdict: GateVerdict;
}

export interface PredictionContract {
  platform: Platform;
  content_id: string;
  scored_at: string;
  gates: GateResult[];
  composite_score: number | null;
  virality_probability: number | null;
  probability_basis: "prior — uncalibrated" | "calibrated";
  wave: { m_hat_per_wave: number[]; ceiling: number | "unbounded" | null };
  projected_views: { h24: number | null; h72: number | null; d7: number | null; d30: number | null };
  weakest_gate: string | null;
  coaching: string | null;
  caveats: string[];
}
